In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets      import load_breast_cancer
from sklearn.model_selection import train_test_split
import numpy as np

In [32]:
from   torch import nn
import torch 
from   torch.nn import functional as f
from  torch.utils.data import TensorDataset, DataLoader

In [33]:
from sklearn.metrics import log_loss, classification_report, accuracy_score

In [34]:
X, y = load_breast_cancer(return_X_y=True)

In [35]:
np.unique(y)

array([0, 1])

In [36]:
X = StandardScaler().fit_transform(X)

In [37]:
X.shape

(569, 30)

In [38]:
class Model(nn.Module):
    def __init__(self, *args, **kwargs) -> None:
        super(Model, self).__init__(*args, **kwargs)
        self.input_  = nn.Linear(in_features=30, out_features=30)
        
        self.hidden_1 = nn.Linear(in_features=30, out_features=15)
        self.hidden_2 = nn.Linear(in_features=15, out_features=6)
        self.hidden_3 = nn.Linear(in_features=6, out_features=3)

        self.output_ = nn.Linear(in_features=3, out_features=1)
    

    def forward(self, x):
        x = f.selu( self.input_(x)  )
        x = f.selu( self.hidden_1(x) )
        x = f.selu( self.hidden_2(x) )
        x = f.selu( self.hidden_3(x) )
        x = f.selu( self.output_(x) )
        return x

In [39]:
model = Model()
model

Model(
  (input_): Linear(in_features=30, out_features=30, bias=True)
  (hidden_1): Linear(in_features=30, out_features=15, bias=True)
  (hidden_2): Linear(in_features=15, out_features=6, bias=True)
  (hidden_3): Linear(in_features=6, out_features=3, bias=True)
  (output_): Linear(in_features=3, out_features=1, bias=True)
)

In [40]:
X = torch.tensor(data=X, dtype=torch.float32)
y = torch.tensor(data=y, dtype=torch.float32).reshape(-1, 1)

In [41]:
data = TensorDataset(X, y)

In [42]:
train = DataLoader(
    dataset=data, batch_size=32, shuffle=True
)
len(X)/32

17.78125

In [45]:
loss  = nn.CrossEntropyLoss()
optim = torch.optim.SGD(
    params = model.parameters(), lr=0.001
)

In [52]:
for epoch in range(10):
    for xtrain, ytrain in train:

        pred = model(xtrain)
        loss_r = loss(ytrain, pred.round())
        
        loss_r.backward()        
        optim.step()
        optim.zero_grad()


   

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.,

In [ ]:
pred = model(X)

tensor(0.0299)
